Código SQL Plataforma de oportunidades - ATUALIZADO.sql

Tipo
SQL
Tamanho
7 KB (7.055 bytes)
Armazenamento usado
7 KB (7.055 bytes)
Local
Etapa 2
Proprietário
Mariana Ruppenthal
Modificado em
23 de ago. de 2018 por Mariana Ruppenthal
Aberto em
12:34 por mim
Criado em
23 de ago. de 2018
Adicionar uma descrição
Os leitores podem fazer o download
-- MySQL Script generated by MySQL Workbench
-- Thu Aug 23 08:10:48 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Endereço`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Endereço` (
  `cod_endereco` INT(9) NOT NULL,
  `Rua` VARCHAR(45) NOT NULL,
  `Numero` SMALLINT(5) NOT NULL,
  `Bairro` VARCHAR(45) NOT NULL,
  `Complemento` VARCHAR(45) NOT NULL,
  `CEP` INT(8) NOT NULL,
  `Cidade` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`cod_endereco`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pessoa` (
  `cod_pessoa` INT(9) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `telefone` BIGINT(11) NOT NULL,
  `ddd` TINYINT(3) NOT NULL,
  `Endereço_cod_endereco` INT(9) NOT NULL,
  PRIMARY KEY (`cod_pessoa`),
  INDEX `fk_Pessoa_Endereço1_idx` (`Endereço_cod_endereco` ASC),
  CONSTRAINT `fk_Pessoa_Endereço1`
    FOREIGN KEY (`Endereço_cod_endereco`)
    REFERENCES `Endereço` (`cod_endereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `PessoaFisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PessoaFisica` (
  `cod_pf` INT(9) NOT NULL,
  `nomeCompleto` VARCHAR(45) NOT NULL,
  `RG` INT(10) NOT NULL,
  `CPF` BIGINT(11) NOT NULL,
  `dataNascimento` DATE NOT NULL,
  `sexo` TINYINT(1) NOT NULL,
  `sexoLiteral` VARCHAR(12) NOT NULL,
  `Pessoa_cod_pessoa` INT(9) NOT NULL,
  PRIMARY KEY (`cod_pf`),
  INDEX `fk_PessoaFisica_Pessoa1_idx` (`Pessoa_cod_pessoa` ASC),
  CONSTRAINT `fk_PessoaFisica_Pessoa1`
    FOREIGN KEY (`Pessoa_cod_pessoa`)
    REFERENCES `Pessoa` (`cod_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Empresa` (
  `cod_empresa` INT(9) NOT NULL,
  `CNPJ` BIGINT(14) NOT NULL,
  `Razão Social` VARCHAR(45) NOT NULL,
  `Nome Fantasia` VARCHAR(45) NOT NULL,
  `Pessoa_cod_pessoa` INT(9) NOT NULL,
  PRIMARY KEY (`cod_empresa`),
  INDEX `fk_Empresa_Pessoa1_idx` (`Pessoa_cod_pessoa` ASC),
  CONSTRAINT `fk_Empresa_Pessoa1`
    FOREIGN KEY (`Pessoa_cod_pessoa`)
    REFERENCES `Pessoa` (`cod_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Aluno` (
  `cod_aluno` INT(9) NOT NULL,
  `matricula` BIGINT(12) NOT NULL,
  `empregado` TINYINT NOT NULL,
  `ano` TINYINT(1) NOT NULL,
  `turno` TINYINT(1) NOT NULL,
  `turnoLiteral` VARCHAR(12) NOT NULL,
  `curso` VARCHAR(45) NOT NULL,
  `PessoaFisica_cod_pf` INT(9) NOT NULL,
  PRIMARY KEY (`cod_aluno`),
  INDEX `fk_Aluno_PessoaFisica1_idx` (`PessoaFisica_cod_pf` ASC),
  CONSTRAINT `fk_Aluno_PessoaFisica1`
    FOREIGN KEY (`PessoaFisica_cod_pf`)
    REFERENCES `PessoaFisica` (`cod_pf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Orientador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Orientador` (
  `cod_orientador` INT(9) NOT NULL,
  `matriculaProf` BIGINT(12) NOT NULL,
  `PessoaFisica_cod_pf` INT(9) NOT NULL,
  PRIMARY KEY (`cod_orientador`),
  INDEX `fk_Orientador_PessoaFisica1_idx` (`PessoaFisica_cod_pf` ASC),
  CONSTRAINT `fk_Orientador_PessoaFisica1`
    FOREIGN KEY (`PessoaFisica_cod_pf`)
    REFERENCES `PessoaFisica` (`cod_pf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Cargo` (
  `cod_cargo` INT(9) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `risco` VARCHAR(45) NOT NULL,
  `setor` VARCHAR(20) NOT NULL,
  `Empresa_cod_empresa` INT(9) NOT NULL,
  PRIMARY KEY (`cod_cargo`),
  INDEX `fk_Cargo_Empresa1_idx` (`Empresa_cod_empresa` ASC),
  CONSTRAINT `fk_Cargo_Empresa1`
    FOREIGN KEY (`Empresa_cod_empresa`)
    REFERENCES `Empresa` (`cod_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Vaga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Vaga` (
  `cod_vaga` INT(9) NOT NULL,
  `descricao` VARCHAR(200) NOT NULL,
  `remunerada` VARCHAR(10) NOT NULL,
  `salario` FLOAT NOT NULL,
  `preenchida` VARCHAR(10) NOT NULL,
  `turno` TINYINT(1) NOT NULL,
  `turnoLiteral` VARCHAR(10) NOT NULL,
  `setor` VARCHAR(45) NOT NULL,
  `oferta` VARCHAR(45) NOT NULL,
  `Cargo_cod_cargo` INT(9) NOT NULL,
  PRIMARY KEY (`cod_vaga`),
  INDEX `fk_Vaga_Cargo1_idx` (`Cargo_cod_cargo` ASC),
  CONSTRAINT `fk_Vaga_Cargo1`
    FOREIGN KEY (`Cargo_cod_cargo`)
    REFERENCES `Cargo` (`cod_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `Estagio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Estagio` (
  `cod_estagio` INT(9) NOT NULL,
  `dataInicio` DATE NOT NULL,
  `dataFim` DATE NOT NULL,
  `supervisor` VARCHAR(45) NOT NULL,
  `Orientador_cod_orientador` INT(9) NOT NULL,
  `Vaga_cod_vaga` INT(9) NOT NULL,
  `Aluno_cod_aluno` INT(9) NOT NULL,
  PRIMARY KEY (`cod_estagio`),
  INDEX `fk_Estagio_Orientador1_idx` (`Orientador_cod_orientador` ASC),
  INDEX `fk_Estagio_Vaga1_idx` (`Vaga_cod_vaga` ASC),
  INDEX `fk_Estagio_Aluno1_idx` (`Aluno_cod_aluno` ASC),
  CONSTRAINT `fk_Estagio_Orientador1`
    FOREIGN KEY (`Orientador_cod_orientador`)
    REFERENCES `Orientador` (`cod_orientador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estagio_Vaga1`
    FOREIGN KEY (`Vaga_cod_vaga`)
    REFERENCES `Vaga` (`cod_vaga`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estagio_Aluno1`
    FOREIGN KEY (`Aluno_cod_aluno`)
    REFERENCES `Aluno` (`cod_aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
